jobs:
  - name: Smith & Partners LLP
    start: July 2018
    prose: |
      Short-term summer job completing record accounts, data entry utilising Excel.
  - name: The Red Lion (Pub)
    start: September 2021
    end: Present
    prose: |
      Behind the bar between BSc and MSc.
    list:
      - Serving drinks and talking to customers.
      - Taking out bins and changing barrels.
